# Generated by Django 4.2.2 on 2023-07-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other'), (4, 'Unknown')], default=4)),
                ('birthday', models.DateField(null=True)),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('job_code', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=50)),
                ('officer_title', models.CharField(max_length=50)),
                ('location_address', models.CharField(max_length=200)),
                ('organization_name_path', models.CharField(max_length=50)),
                ('organization_code_path', models.CharField(max_length=50)),
                ('level', models.SmallIntegerField(choices=[(-1, 'No Level'), (0, 'SVCNTS'), (1, 'L1'), (2, 'L2'), (3, 'L3')], default=-1)),
                ('created_by', models.CharField(editable=False)),
                ('updated_by', models.CharField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('date_in', models.DateField(default=None, null=True)),
                ('date_out', models.DateField(default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
