# Generated by Django 4.2.2 on 2023-07-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='manages',
            field=models.ManyToManyField(null=True, to='Employee.employee'),
        ),
    ]
