# Generated by Django 4.2.2 on 2023-07-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_employee_manages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='manages',
            field=models.ManyToManyField(blank=True, null=True, to='Employee.employee'),
        ),
    ]
