# Generated by Django 4.2.2 on 2023-07-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
