# Generated by Django 4.2.2 on 2023-07-03 08:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('formula_name', models.CharField(max_length=50)),
                ('formula_value', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('objective_name', models.CharField(max_length=50)),
                ('objective_content', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OKR',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key_result_name', models.CharField(max_length=50)),
                ('key_result_content', models.TextField(max_length=200)),
                ('type', models.CharField(choices=[('OKR', 'OKR'), ('KPI', 'KPI')])),
                ('regularity', models.CharField(choices=[('MO', 'MONTHLY'), ('QUAR', 'QUARTERLY')])),
                ('unit', models.CharField(max_length=20)),
                ('condition', models.IntegerField()),
                ('norm', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('result', models.IntegerField()),
                ('ratio', models.IntegerField()),
                ('status', models.CharField(choices=[('S', 'Satisfactory'), ('NS', 'Not Satisfactory'), ('INP', 'In Progress')])),
                ('created_by', models.CharField(max_length=30)),
                ('updated_by', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=10)),
                ('formula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OKR.formula')),
                ('objective_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OKR.objective')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OKR.source')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(max_length=200)),
                ('created_by', models.CharField(max_length=30)),
                ('updated_by', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('okr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OKR.okr')),
            ],
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key_result_name', models.CharField(max_length=50)),
                ('key_result_content', models.TextField(max_length=200)),
                ('okr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OKR.okr')),
            ],
        ),
    ]
