# Generated by Django 4.2.2 on 2023-07-18 07:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('formula_name', models.CharField(max_length=50)),
                ('formula_value', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('objective_name', models.CharField(max_length=50)),
                ('objective_content', models.TextField(default='To be filled', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OKR',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('key_result_department', models.TextField(default='department', max_length=200)),
                ('key_result_team', models.TextField(default='team', max_length=200)),
                ('key_result_personal', models.TextField(default='personal', max_length=200)),
                ('type', models.CharField(choices=[('OKR', 'OKR'), ('KPI', 'KPI')])),
                ('regularity', models.CharField(choices=[('MO', 'MONTHLY'), ('QUAR', 'QUARTERLY')])),
                ('unit', models.CharField(choices=[('NUM', 'NUMERIC'), ('CAT', 'CATEGORICAL')])),
                ('condition', models.CharField(choices=[('LESS', 'LESS THAN'), ('MORE', 'MORE THAN'), ('EQUAL', 'EQUAL'), ('LOE', 'LESS OR EQUAL'), ('MOE', 'MORE OR EQUAL')])),
                ('norm', models.IntegerField()),
                ('weight', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('result', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('ratio', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('estimated', models.CharField(max_length=200, null=True)),
                ('actual', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending Approval'), ('INP', 'In Progress'), ('S', 'Satisfactory'), ('NS', 'Not Satisfactory')], default='P')),
                ('created_by', models.CharField(editable=False, max_length=30)),
                ('updated_by', models.CharField(default=None, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('deadline_quarter', models.CharField(choices=[('Q1', 'First Quarter'), ('Q2', 'Second Quarter'), ('Q3', 'Third Quarter'), ('Q4', 'Fourth Quarter')], editable=False, null=True)),
                ('deadline_month', models.IntegerField(editable=False, null=True)),
                ('deadline_year', models.CharField(editable=False, null=True)),
                ('files', models.URLField(blank=True, null=True)),
                ('formula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OKR.formula')),
                ('objective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OKR.objective')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OKR.source')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(max_length=200)),
                ('created_by', models.CharField(max_length=30)),
                ('updated_by', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('okr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OKR.okr')),
            ],
        ),
    ]
