# Generated by Django 4.2.2 on 2023-07-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OKR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='objective_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
