# Generated by Django 4.2.2 on 2023-07-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OKR', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
    ]
