# Generated by Django 4.2.2 on 2023-07-18 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OKR', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okr',
            name='user',
        ),
    ]
