# Generated by Django 4.2.2 on 2023-07-04 04:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OKR', '0002_rename_logs_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okr',
            name='condition',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='okr',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 4, 52, 45, 330200)),
        ),
        migrations.AlterField(
            model_name='okr',
            name='files',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='okr',
            name='ratio',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='okr',
            name='regularity',
            field=models.CharField(choices=[('MO', 'MONTHLY'), ('QUAR', 'QUARTERLY')], editable=False),
        ),
        migrations.AlterField(
            model_name='okr',
            name='result',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='okr',
            name='status',
            field=models.CharField(choices=[('P', 'Pending Approval'), ('INP', 'In Progress'), ('S', 'Satisfactory'), ('NS', 'Not Satisfactory')], default='P'),
        ),
        migrations.AlterField(
            model_name='okr',
            name='type',
            field=models.CharField(choices=[('OKR', 'OKR'), ('KPI', 'KPI')], editable=False),
        ),
        migrations.AlterField(
            model_name='okr',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
