# Generated by Django 4.2.2 on 2023-07-04 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OKR', '0003_alter_okr_condition_alter_okr_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okr',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
