# Generated by Django 4.2.2 on 2023-07-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("OKR", "0003_alter_okr_ratio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="okr",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
